export const CHECKLIST_SECTIONS = [
  {
    id: 'wake',
    label: 'WAKE',
    items: [
      'Alex woke up, went to the bathroom, and went back to bed.',
      'Alex woke back up and got up for the day.',
      'Alex woke on her own and took herself to the bathroom.',
      'Alex slept in.',
      'Sponsor/Relief woke Alex.',
    ],
  },
  {
    id: 'morning',
    label: 'MORNING',
    items: [
      'Sponsor/Relief helped Alex get dressed and brush her teeth and hair.',
      'Sponsor/Relief helped Alex brush her teeth and hair.',
      'Alex picked __OUTFIT__ from the outfits hanging outside her dresser.',
      'Sponsor/Relief helped Alex pick out an outfit from the ones hanging outside her dresser.',
      'Alex put her shoes on the wrong feet and Sponsor/Relief helped her put them on right.',
      'Alex put her dress on backwards and Sponsor/Relief helped her put it on right.',
      'Alex cleaned her room and organized her shelves. Sponsor/Relief checked on Alex until she completed her chores.',
    ],
  },
  {
    id: 'breakfast',
    label: 'BREAKFAST',
    items: [
      'Sponsor/Relief prepared breakfast, monitored Alex as she ate and administered AM meds.',
      'While eating, Sponsor/Relief and Alex discussed the menu for the upcoming week and made a small shopping list.',
      'Alex helped clear the table.',
      'Sponsor/Relief made Alex tea and made sure it was the right temperature.',
      'Alex watched TV until the van arrived.',
      'Alex drank her tea until the van arrived.',
    ],
  },
  {
    id: 'diversityVan',
    label: 'DIVERSITY VAN',
    weekdayOnly: true,
    items: [
      'Van arrived to take Alex to Diversity.',
      'Van returned with Alex.',
    ],
  },
  {
    id: 'kiearra',
    label: 'KIEARRA (SAT)',
    items: [
      "Kiearra arrived to take Alex out for a girl's day.",
      '__KIEARRA_ACTIVITIES__',
      'Kiearra returned Alex home.',
    ],
  },
  {
    id: 'midday',
    label: 'MIDDAY',
    items: [
      '__MIDDAY_CUSTOM__',
      'Sponsor/Relief and Alex took Izzy for a quick neighborhood walk.',
      'Sponsor/Relief and Alex took Izzy to Huguenot Park. Alex walked 1.5 miles.',
      'Sponsor/Relief and Alex took Izzy to Grove Park. Alex walked 2 laps around the lake.',
      'Sponsor/Relief and Alex took Izzy to the water tower to walk a couple laps around the track.',
      'Sponsor/Relief and Alex took Izzy to the senior center to chase balls. Alex walked several laps around the field.',
      'Sponsor/Relief and Alex took Izzy back home.',
      'Sponsor/Relief and Alex worked on making bead bracelets while watching TV.',
      'Sponsor/Relief asked Alex if she wanted to work on a __CAD_OFFERED__ craft. Alex said yes and chose __CAD_CHOSE__. Sponsor/Relief set Alex up with __CAD_CHOSE__ in the family room and checked in on her as she worked.',
      'Alex cleaned her room and organized her shelves. Sponsor/Relief checked on Alex until she completed her chores.',
      'Alex helped Sponsor/Relief fold and put away some laundry.',
      'Alex helped Sponsor/Relief put dirty laundry in the washer and dryer.',
      'Sponsor/Relief and Alex picked out outfits for the upcoming week at Diversity and hung them outside her dresser.',
      'Sponsor/Relief asked Alex if she wanted to go to Target. Alex said yes. Alex helped push the buggy and carry the bags to the car as she was able.',
      'Sponsor/Relief and Alex went to Wegmans. Alex helped push the cart and helped carry bags to the car as she was able.',
      'Sponsor/Relief and Alex watched a movie on TV.',
      'Sponsor/Relief ran a fire drill, helped Alex respond to the alarm and helped Alex evacuate to the meeting place in the front yard.',
    ],
  },
  {
    id: 'lunch',
    label: 'LUNCH',
    items: [
      'Sponsor/Relief prepared lunch and monitored Alex as she ate.',
      'Alex watched a little TV while Sponsor/Relief prepared lunch.',
      'Alex helped Sponsor/Relief cook home-made granola.',
      'Alex helped clear the table.',
    ],
  },
  {
    id: 'afterLunch',
    label: 'AFTER LUNCH',
    items: [
      '__AFTER_LUNCH_CUSTOM__',
      'Sponsor/Relief and Alex took Izzy for a quick neighborhood walk.',
      'Sponsor/Relief and Alex took Izzy to Huguenot Park. Alex walked 1.5 miles.',
      'Sponsor/Relief and Alex took Izzy to Grove Park. Alex walked 2 laps around the lake.',
      'Sponsor/Relief and Alex took Izzy to the water tower to walk a couple laps around the track.',
      'Sponsor/Relief and Alex took Izzy to the senior center to chase balls. Alex walked several laps around the field.',
      'Sponsor/Relief and Alex took Izzy back home.',
      'Sponsor/Relief and Alex worked on making bead bracelets while watching TV.',
      'Sponsor/Relief asked Alex if she wanted to work on a __CAD_OFFERED__ craft. Alex said yes and chose __CAD_CHOSE__. Sponsor/Relief set Alex up with __CAD_CHOSE__ in the family room and checked in on her as she worked.',
      'Alex cleaned her room and organized her shelves. Sponsor/Relief checked on Alex until she completed her chores.',
      'Alex helped Sponsor/Relief fold and put away some laundry.',
      'Alex helped Sponsor/Relief put dirty laundry in the washer and dryer.',
      'Sponsor/Relief and Alex picked out outfits for the upcoming week at Diversity and hung them outside her dresser.',
      'Sponsor/Relief asked Alex if she wanted to go to Target. Alex said yes. Alex helped push the buggy and carry the bags to the car as she was able.',
      'Sponsor/Relief and Alex went to Wegmans. Alex helped push the cart and helped carry bags to the car as she was able.',
      'Sponsor/Relief and Alex watched a movie on TV.',
      'Sponsor/Relief ran a fire drill, helped Alex respond to the alarm and helped Alex evacuate to the meeting place in the front yard.',
    ],
  },
  {
    id: 'dinner',
    label: 'DINNER',
    items: [
      'Sponsor/Relief prepared dinner, monitored Alex as she ate and administered PM meds.',
      'Sponsor/Relief prepared dinner while Alex watched TV, monitored Alex as she ate and administered PM meds.',
      'Sponsor/Relief administered PM meds.',
      'Alex helped clear the table.',
    ],
  },
  {
    id: 'evening',
    label: 'EVENING',
    items: [
      '__EVENING_CUSTOM__',
      'Sponsor/Relief and Alex took Izzy for a quick neighborhood walk.',
      'Sponsor/Relief and Alex took Izzy to Huguenot Park. Alex walked 1.5 miles.',
      'Sponsor/Relief and Alex took Izzy to Grove Park. Alex walked 2 laps around the lake.',
      'Sponsor/Relief and Alex took Izzy to the water tower to walk a couple laps around the track.',
      'Sponsor/Relief and Alex took Izzy to the senior center to chase balls. Alex walked several laps around the field.',
      'Sponsor/Relief and Alex took Izzy back home.',
      'Sponsor/Relief and Alex worked on making bead bracelets while watching TV.',
      'Sponsor/Relief asked Alex if she wanted to work on a __CAD_OFFERED__ craft. Alex said yes and chose __CAD_CHOSE__. Sponsor/Relief set Alex up with __CAD_CHOSE__ in the family room and checked in on her as she worked.',
      'Alex cleaned her room and organized her shelves. Sponsor/Relief checked on Alex until she completed her chores.',
      'Alex helped Sponsor/Relief fold and put away some laundry.',
      'Alex helped Sponsor/Relief put dirty laundry in the washer and dryer.',
      'Sponsor/Relief and Alex picked out outfits for the upcoming week at Diversity and hung them outside her dresser.',
      'Sponsor/Relief asked Alex if she wanted to go to Target. Alex said yes. Alex helped push the buggy and carry the bags to the car as she was able.',
      'Sponsor/Relief and Alex went to Wegmans. Alex helped push the cart and helped carry bags to the car as she was able.',
      'Sponsor/Relief and Alex watched a movie on TV.',
      'Sponsor/Relief ran a fire drill, helped Alex respond to the alarm and helped Alex evacuate to the meeting place in the front yard.',
    ],
  },
  {
    id: 'bed',
    label: 'BED',
    items: [
      'Sponsor/Relief helped Alex shower and with ADLs and helped Alex put on PJs.',
      'Sponsor/Relief helped Alex brush her teeth and hair and put on PJs.',
      'Alex watched TV with Sponsor and Relief until she was tired and went to bed.',
      'Alex went to bed.',
    ],
  },
]